import { Router, Request, Response } from 'express';
import { generateFileContent, generateProject } from '../services/generateService.js';
import { FileNode, GenerateRequest } from '../types/index.js';

export const generateRouter = Router();

generateRouter.post('/file', (req: Request, res: Response) => {
  const { node, language, framework } = req.body as {
    node: FileNode;
    language: string;
    framework: string;
  };

  if (!node || !language || !framework) {
    res.status(400).json({ error: 'node, language, and framework are required' });
    return;
  }

  try {
    const content = generateFileContent(node, language, framework);
    res.json({ content });
  } catch (error) {
    res.status(500).json({ error: `Code generation failed: ${(error as Error).message}` });
  }
});

generateRouter.post('/project', (req: Request, res: Response) => {
  const request = req.body as GenerateRequest;

  if (!request.files || !request.language || !request.framework) {
    res.status(400).json({ error: 'files, language, and framework are required' });
    return;
  }

  try {
    const files = generateProject(request);
    res.json({ files });
  } catch (error) {
    res.status(500).json({ error: `Project generation failed: ${(error as Error).message}` });
  }
});

generateRouter.post('/scaffold', (req: Request, res: Response) => {
  const { projectName, language, framework, fileTypes } = req.body as {
    projectName: string;
    language: string;
    framework: string;
    fileTypes: string[];
  };

  if (!projectName || !language || !framework) {
    res.status(400).json({ error: 'projectName, language, and framework are required' });
    return;
  }

  try {
    const scaffold = generateScaffold(projectName, language, framework, fileTypes || []);
    res.json({ scaffold });
  } catch (error) {
    res.status(500).json({ error: `Scaffold generation failed: ${(error as Error).message}` });
  }
});

function generateScaffold(
  projectName: string,
  language: string,
  framework: string,
  fileTypes: string[]
): Record<string, string> {
  const ext = language === 'typescript' ? 'ts' : language === 'python' ? 'py' : 'js';
  const componentExt = language === 'typescript' ? 'tsx' : language === 'python' ? 'py' : 'jsx';
  const result: Record<string, string> = {};

  if (framework === 'react' || framework === 'nextjs') {
    if (!fileTypes.length || fileTypes.includes('component')) {
      result[`src/components/App.${componentExt}`] = `import React from 'react';

const App: React.FC = () => {
  return (
    <div className="app">
      <h1>${projectName}</h1>
    </div>
  );
};

export default App;
`;
    }
    if (!fileTypes.length || fileTypes.includes('service')) {
      result[`src/services/api.${ext}`] = `const BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:3000';

export async function fetchData<T>(endpoint: string): Promise<T> {
  const response = await fetch(\`\${BASE_URL}\${endpoint}\`);
  if (!response.ok) throw new Error(\`HTTP error \${response.status}\`);
  return response.json() as Promise<T>;
}
`;
    }
  } else if (framework === 'express') {
    if (!fileTypes.length || fileTypes.includes('controller')) {
      result[`src/controllers/index.${ext}`] = `import { Router, Request, Response } from 'express';

export const router = Router();

router.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', project: '${projectName}' });
});
`;
    }
    if (!fileTypes.length || fileTypes.includes('service')) {
      result[`src/services/index.${ext}`] = `export class ${projectName.charAt(0).toUpperCase() + projectName.slice(1)}Service {
  async initialize(): Promise<void> {
    // Initialize service
  }
}

export const service = new ${projectName.charAt(0).toUpperCase() + projectName.slice(1)}Service();
`;
    }
  } else if (framework === 'django' || framework === 'flask') {
    result[`${projectName}/models.py`] = `from django.db import models\n\n# Create your models here.\n`;
    result[`${projectName}/views.py`] = `from django.shortcuts import render\n\n# Create your views here.\n`;
  }

  result[`README.md`] = `# ${projectName}

Generated by Code by Design.

## Language
${language}

## Framework
${framework}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

  return result;
}
